name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run file check on jpg
        run: |
          for file in $(find . -name "*.jpg"); do
            file "$file"
          done

  build-memory:
    needs: test-memory
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t phonaxy/memory .


  push-memory:
    needs: build-memory
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push phonaxy/memory

  deploy-memory:
    needs: push-memory
    runs-on: self-hosted
    steps:
      - name: SSH to server and deploy
        run: |
          ssh user@your-server "docker pull phonaxy/memory && docker run -d -p 80:80 phonaxy/memory"
