name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run file check on jpg
        run: |
          for file in $(find . -name "*.jpg"); do
            file "$file"
          done
